const SEARCH_INPUT = 'SEARCH_INPUT'
const FINDING_QUESTION = 'FINDING_QUESTION'
const FOUND_QUESTION = 'FOUND_QUESTION'
const COULD_NOT_FOUND_QUESTION = 'COULD_NOT_FOUND_QUESTION'
const GET_QUESTIONS = 'GET_QUESTIONS'
const GETTING_QUESTIONS = 'RECEIVED_QUESTIONS'
const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED'

export default {
    SEARCH_INPUT,
    FINDING_QUESTION,
    FOUND_QUESTION,
    COULD_NOT_FOUND_QUESTION,
    GET_QUESTIONS,
    GETTING_QUESTIONS,
    GET_QUESTIONS_FAILED,
    GET_QUESTIONS_SUCCESS
}