const SEARCH_INPUT = 'SEARCH_INPUT'
const MESSAGE_INPUT = 'MESSAGE_INPUT'
const FINDING_QUESTION = 'FINDING_QUESTION'
const FOUND_QUESTION = 'FOUND_QUESTION'
const COULD_NOT_FOUND_QUESTION = 'COULD_NOT_FOUND_QUESTION'
const GET_QUESTIONS = 'GET_QUESTIONS'
const GETTING_QUESTIONS = 'RECEIVED_QUESTIONS'
const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED'
const GET_CHATBOT = 'GET_CHATBOT'
const GETTING_CHATBOT = 'GETTING_CHATBOT'
const GET_CHATBOT_SUCCESS = 'GET_CHATBOT_SUCCESS'
const GET_CHATBOT_FAILED = 'GET_CHATBOT_FAILED'
const CALL_CHATBOT = 'CALL_CHATBOT' 
const CAPTURE_ACTION = 'CAPTURE_ACTION'
const SEND_MESSAGE_TO_BOT = 'SEND_MESSAGE_TO_BOT'
const SENDING_MESSAGE_TO_BOT = 'SENDING_MESSAGE_TO_BOT'
const SEND_MESSAGE_TO_BOT_SUCCESS = 'SEND_MESSAGE_TO_BOT_SUCCESS'
const SEND_MESSAGE_TO_BOT_FAILURE = 'SEND_MESSAGE_TO_BOT_FAILURE'
const HANDLE_ACTION = 'HANDLE_ACTION'

export default {
    SEARCH_INPUT,
    MESSAGE_INPUT,
    FINDING_QUESTION,
    FOUND_QUESTION,
    COULD_NOT_FOUND_QUESTION,
    GET_QUESTIONS,
    GETTING_QUESTIONS,
    GET_QUESTIONS_FAILED,
    GET_QUESTIONS_SUCCESS,
    GET_CHATBOT,
    GETTING_CHATBOT,
    GET_CHATBOT_SUCCESS,
    GET_CHATBOT_FAILED,
    CALL_CHATBOT,
    CAPTURE_ACTION,
    SEND_MESSAGE_TO_BOT,
    SENDING_MESSAGE_TO_BOT,
    SEND_MESSAGE_TO_BOT_SUCCESS,
    SEND_MESSAGE_TO_BOT_FAILURE,
    HANDLE_ACTION
}